{% set name = "dagster-async-executor" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dagster_async_executor-{{ version }}.tar.gz
  sha256: 1801398b6086280cd2bb3af0a149ccf18f0cdb1bfdb8bcee9c6085e112ae16b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - python >={{ python_min }},<4.0
    - anyio >=4.12.0
    - dagster >=1.12.2

test:
  imports:
    - dagster_async_executor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Async Support for Dagster
  license: 'Apache-2.0'
  license_file: LICENSE
  home: https://github.com/dagster-io/community-integrations

extra:
  recipe-maintainers:
    - rxm7706
